cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:product_id>/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('delete_cart_item/<int:product_id>/<int:cart_item_id>/', views.delete_cart_item, name='delete_cart_item'),

    path('checkout/', views.checkout, name='checkout'),
    
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [

	path('place_order/', views.place_order, name='place_order'),
	path('payment/', views.payment, name='payment'),
	path('order_completed/', views.order_completed, name='order_completed'),
	path('order_details/<int:order_id>/', views.order_details, name='order_details'),

]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [

    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='product_by_categroy'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_details, name='product_details'),
    path('search/', views.search, name='search'),
   path('submitreview/<int:product_id>/', views.submit_review, name='submit_review'),

]

cart/models.py
from django.db import models
from store.models import Product, Variation
from accounts.models import Account
# Create your models here.


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    product_variation = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quality = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.product.product_name

    def sub_total(self):
        return self.product.price * self.quality

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from store.models import Product, Variation
from cart.models import Cart, CartItem
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.!


def _cart_id(request):

    cart_id = request.session.session_key
    if not cart_id:
        cart_id = request.session.create()
    return cart_id

def add_to_cart(request, product_id):

    current_user = request.user
    product = Product.objects.get(id=product_id)
    product_variation = []

    if current_user.is_authenticated:

        if request.method == 'POST':

            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(product=product_id, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)

                except:
                    pass

        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))

        except:

            cart = Cart.objects.create(cart_id=_cart_id(request))
            cart.save()

        cart_item_exist = CartItem.objects.filter(product=product, user=current_user).exists()

        if cart_item_exist:
            cart_items = CartItem.objects.filter(product=product, user=current_user)
            ex_variation_list = []
            cart_item_id = []
            
            for cart_item in cart_items:
                existing_variation = cart_item.product_variation.all()
                ex_variation_list.append(list(existing_variation))
                cart_item_id.append(cart_item.id)

            if product_variation in ex_variation_list:

                index = ex_variation_list.index(product_variation)
                cart_item_id = cart_item_id[index]
                cart_item = CartItem.objects.get(product=product, id=cart_item_id)
                cart_item.quality += 1
                cart_item.save()
                messages.success(request, 'Product Quantity Updated.')
            
            else:

                cart_item = CartItem.objects.create(product=product, user=current_user, quality=1)
                if len(product_variation) > 0:
                    cart_item.product_variation.add(*product_variation)
                else:
                    pass
                cart_item.save()
                messages.success(request, f'{product.product_name} Added to Cart.')
        else:

            cart_item = CartItem.objects.create(product=product, user=current_user, quality=1)
            if len(product_variation) > 0:
                cart_item.product_variation.add(*product_variation)
                cart_item.save()
            messages.success(request, f'{product.product_name} Added to Cart.')
            

        return redirect('cart:cart')

    else:

        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(product=product_id, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)

                except:
                    pass

        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))
        except:
            cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()

        cart_item_exist = CartItem.objects.filter(product=product, cart=cart).exists()

        if cart_item_exist:
            cart_items = CartItem.objects.filter(product=product, cart=cart)
            ex_variation_list = []
            cart_item_id = []
            
            for cart_item in cart_items:
                existing_variation = cart_item.product_variation.all()
                ex_variation_list.append(list(existing_variation))
                cart_item_id.append(cart_item.id)

            if product_variation in ex_variation_list:
                index = ex_variation_list.index(product_variation)
                cart_item_id = cart_item_id[index]
                cart_item = CartItem.objects.get(product=product, id=cart_item_id)
                cart_item.quality += 1
                cart_item.save()
                messages.success(request, 'Product Quantity Updated.')
            
            else:
                cart_item = CartItem.objects.create(product=product, cart=cart, quality=1)
                if len(product_variation) > 0:
                    cart_item.product_variation.add(*product_variation)
                else:
                    pass
                cart_item.save()
                messages.success(request, f'{product.product_name} Added to Cart.')
        else:
            cart_item = CartItem.objects.create(product=product, cart=cart, quality=1)
            if len(product_variation) > 0:
                cart_item.product_variation.add(*product_variation)
            cart_item.save()
            messages.success(request, f'{product.product_name} Added to Cart.')
            

        return redirect('cart:cart')


def remove_from_cart(request, product_id, cart_item_id):

    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except:
        cart = None
    product = Product.objects.get(id=product_id)


    try:
        if request.user.is_authenticated:
            cart_item =  CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)

        if cart_item.quality > 1:
            cart_item.quality -= 1
            cart_item.save()
            messages.success(request, 'Product Quantity Updated.')
        else:
            cart_item.delete()
            messages.success(request, f'{product.product_name} has been removed.')
    except:
        pass

    return redirect('cart:cart')


def delete_cart_item(request, product_id, cart_item_id):

    product = Product.objects.get(id=product_id)

    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        
    cart_item.delete()
    messages.success(request, f'{product.product_name} has beem removed.')

    return redirect('cart:cart')


def cart(request, total=0, quantity=0, cart_items=None, tax=None, grand_total=None):

    try:

        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quality)
            quantity = cart_item.quality

        tax = (total / 100) * 2
        grand_total = total + tax

    except:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
    }

    return render(request, 'cart/cart.html', context)



@login_required(login_url='accounts:log_in')
def checkout(request, total=0, quantity=0, cart_items=None, tax=None, grand_total=None):

    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user)
        
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quality)
            quantity = cart_item.quality

        tax = (total / 100) * 2
        grand_total = total + tax

    except:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
    }

    return render(request, 'cart/checkout.html', context)


 

templates/cart/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="section-content padding-y bg">
<div class="container">

	{% if not cart_items %}
		<h3 class="text-center"> Your shopping cart is empty </h3>
		<br>
		<div class="text-center">  
			<a href="{% url 'store:store' %}" class="btn btn-primary">Continue shopping</a>
		</div> 
	{% else %}


<!-- ============================ COMPONENT 1 ================================= -->
<div class="row">
	<aside class="col-lg-9">
<div class="card">
<table class="table table-borderless table-shopping-cart">
<thead class="text-muted">
<tr class="small text-uppercase">
  <th scope="col">Product</th>
  <th scope="col" width="120">Quantity</th>
  <th scope="col" width="120">Total</th>
  <th scope="col" class="text-right" width="200"> </th>
</tr>
</thead>
<tbody>

	{% for cart_item in cart_items %}

<tr>
	<td>
		<figure class="itemside align-items-center">
			<div class="aside"><img src="{{cart_item.product.images.url}}" class="img-sm"></div>
			<figcaption class="info">
				<a href="{{ cart_item.product.get_url }}" class="title text-dark">{{cart_item.product.product_name}}</a>
				<p class="text-muted small">
					{% if cart_item.product_variation.all %}
						{% for variation in cart_item.product_variation.all %}
						{{variation.variation_category | capfirst}} : {{variation.variation_value | capfirst}} <br>
						{% endfor %}
					{% endif %}
				</p>
			</figcaption>
		</figure>
	</td>
	<td> 
		<!-- col.// -->
					<div class="col"> 
						<div class="input-group input-spinner">
							<div class="input-group-prepend">
							<a href="{% url 'cart:remove_from_cart' cart_item.product.id cart_item.id %}" class="btn btn-light" type="button" id="button-plus"> 
								<i class="fa fa-minus"></i> 
							</a>
							</div>
							<input type="text" class="form-control"  value="{{cart_item.quality}}">
							<div class="input-group-append">
							<form action="{% url 'cart:add_to_cart' cart_item.product.id %}" method="POST">
									{% csrf_token %}
									{% for item in cart_item.product_variation.all %}
									<input type="hidden" name="{{item.variation_category | lower}}" value="{{item.variation_value | capfirst}}">
									{% endfor %}
									<button class="btn btn-light" type="submit" id="button-minus"> <i class="fa fa-plus"></i> </button>
							</form>
							
							</div>
						</div> <!-- input-group.// -->
					</div> <!-- col.// -->
	</td>
	
	<td> 
		<div class="price-wrap"> 
			<var class="price">${{cart_item.sub_total}}</var> 
			<small class="text-muted"> ${{cart_item.product.price}} each</small> 
		</div> <!-- price-wrap .// -->
	</td>
	<td class="text-right"> 
		<a href="{% url 'cart:delete_cart_item' cart_item.product.id cart_item.id %}" class="btn btn-danger"> Remove</a>
	</td>

</tr>
{% endfor %}
</tbody>
</table>
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-3">

		<div class="card">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Total price:</dt>
			  <dd class="text-right">${{total}}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Tax:</dt>
			  <dd class="text-right"> ${{tax}}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Grand Total:</dt>
			  <dd class="text-right text-dark b"><strong>${{grand_total}}</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src="{% static './images/misc/payments.png' %}" height="26">
			</p>
			<a href="{% url 'cart:checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
			<a href="{% url 'store:store' %}" class="btn btn-light btn-block">Continue Shopping</a>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside> <!-- col.// -->


</div> <!-- row.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->
{% endif %}
</div> <!-- container .//  -->

</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/cart/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="section-content padding-y bg">
<form action="{% url 'orders:place_order' %}" method="POST">
{% csrf_token %}
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
<div class="row">
<aside class="col-lg-6">
<div class="card">
	<div class="card-body">

		<h4 class="card-title mb-4">Billing Address </h4>
		
			<div class="form-row">
				<div class="col form-group">
					<label for=""> First Name</label>
					<input type="text" name="first_name" class="form-control" required> 
				</div> 

				<div class="col form-group">
					<label for=""> Last Name</label>
					<input type="text" name="last_name" class="form-control" required> 
				</div> 
			</div>
		
			<div class="form-row">

				<div class="col form-group">
					<label for=""> Email</label>
					<input type="email" name="email" class="form-control" required> 
				</div> 

				<div class="col form-group">
					<label for=""> Phone Number </label>
					<input type="text" name="phone" class="form-control" required> 
				</div> 

			</div>
		
			<div class="form-row">

				<div class="col form-group">
					<label for=""> Address Line 1</label>
					<input type="text" name="address_line_1" class="form-control" required> 
				</div> 

				<div class="col form-group">
					<label for=""> Address Line 2 </label>
					<input type="text" name="address_line_2" class="form-control"> 
				</div> 

			</div>

			<div class="form-row">

				<div class="col form-group">
					<label for=""> City</label>
					<input type="text" name="city" class="form-control" required> 
				</div> 

				<div class="col form-group">
					<label for=""> State </label>
					<input type="text" name="state" class="form-control" required> 
				</div>

				<div class="col form-group">
					<label for=""> Country </label>
					<input type="text" name="country" class="form-control" required> 
				</div>

			</div>

			<div class="form-row">

				<div class="col form-group">
					<label for="">Order Note</label>
					<textarea rows="3" name="order_note" class="form-control"> </textarea>
				</div> 

			</div>

	</div>
</div> <!-- card.// -->
</aside> <!-- col.// -->


	<aside class="col-lg-6">
	<table class="table table-borderless table-shopping-cart">
		<thead class="text-muted" style="text-align: center;">
			<tr class="small text-uppercase">
			  <th scope="col">Product</th>
			  <th scope="col" width="120">Quantity</th>
			  <th scope="col" width="120">Total</th>
			  <th scope="col" class="text-right" width="200"> </th>
			</tr>
		</thead>
	<tbody>

	{% for cart_item in cart_items %}

	<tr style="text-align: center;">
		<td class="col-lg-7">
			<figure class="itemside align-items-center">
				<div class="aside"><img src="{{cart_item.product.images.url}}" class="img-sm"></div>
				<figcaption class="info">
					<a href="{{ cart_item.product.get_url }}" class="title text-dark">{{cart_item.product.product_name}}</a>
					<p class="text-muted small">
						{% if cart_item.product_variation.all %}
							{% for variation in cart_item.product_variation.all %}
							{{variation.variation_category | capfirst}} : {{variation.variation_value | capfirst}} <br>
							{% endfor %}
						{% endif %}
					</p>
				</figcaption>
			</figure>
		</td>
		<td class="col-lg-2" style="padding-top: 3rem;"> 
			<!-- col.// -->
								<h6> {{cart_item.quality}} </h6>
								<div class="input-group-append">
								<form action="{% url 'cart:add_to_cart' cart_item.product.id %}" method="POST">
										{% csrf_token %}
										{% for item in cart_item.product_variation.all %}
										<input type="hidden" name="{{item.variation_category | lower}}" value="{{item.variation_value | capfirst}}">
										{% endfor %}
								</form>
								
								</div>
							</div> <!-- input-group.// -->
						</div> <!-- col.// -->
		</td>
		
		<td class="col-lg-3" style="padding-top: 2.5rem;"> 
			<div class="price-wrap"> 
				<var class="price">${{cart_item.sub_total}}</var> 
				<small class="text-muted"> ${{cart_item.product.price}} each</small> 
			</div> <!-- price-wrap .// -->
		</td>
	</tr>
	{% endfor %}
	</tbody>
	</table>
		<div class="card">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Total price:</dt>
			  <dd class="text-right">${{total}}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Tax:</dt>
			  <dd class="text-right"> ${{tax}}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Grand Total:</dt>
			  <dd class="text-right text-dark b"><strong>${{grand_total}}</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src="{% static './images/misc/payments.png' %}" height="26">
			</p>
			<center> <button type="submit" class="btn btn-primary btn-block" name="submit" style="width: 300px"> Place Order </button> </center>
			<center>	<a href="{% url 'store:store' %}" class="btn btn-light btn-block mt-3" style="width: 300px;">Continue Shopping</a> </center>

		</div> <!-- card-body.// -->
		</div> <!-- card.// -->
	
</aside> <!-- col.// -->
</div> <!-- row.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->
</div> <!-- container .//  -->
</form>
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}