accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [

	path('register/', views.register, name='register'),
	path('log_in/', views.log_in, name='log_in'),
	path('log_out/', views.log_out, name='log_out'),
	path('reset_password/', views.reset_password, name='reset_password'),
	
	path('activate/<uidb64>/<token>/', views.activate, name='activate'),
	path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),
	path('reset_password_process/', views.reset_password_process, name='reset_password_process'),
	path('', views.dashboard, name='dashboard'),
	path('my_orders/', views.my_orders, name='my_orders'),
	path('edit_profile/', views.edit_profile, name='edit_profile'),
	path('change_password/', views.change_password, name='change_password'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:product_id>/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('delete_cart_item/<int:product_id>/<int:cart_item_id>/', views.delete_cart_item, name='delete_cart_item'),

    path('checkout/', views.checkout, name='checkout'),
    
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [

	path('place_order/', views.place_order, name='place_order'),
	path('payment/', views.payment, name='payment'),
	path('order_completed/', views.order_completed, name='order_completed'),
	path('order_details/<int:order_id>/', views.order_details, name='order_details'),

]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db.models import Avg,Count
# Create your models  here.


class MyAccountManager(BaseUserManager):

    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('User must have an email address.')

        user = self.model(

            email=self.normalize_email(email),
            **extra_fields
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **extra_fields):

        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superadmin', True)
        extra_fields.setdefault('is_admin', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superadmin') is not True:
            raise ValueError(('is_superadmin must have is_superadmin=True.'))
        return self.create_user(email=email, password=password, **extra_fields)


class Account(AbstractBaseUser):

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=20)
    # required
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELD = ['username', 'first_name', 'last_name', 'password', 'confirm_password']

    objects = MyAccountManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def profile_image(self):
        userprofile =  UserProfile.objects.get(user=self)
        return userprofile.profile_image


class UserProfile(models.Model):
    
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    address_line_1 = models.CharField(blank=True, max_length=200)
    address_line_2 = models.CharField(max_length=200, blank=True)
    profile_image = models.ImageField(upload_to='photos/user/profile', default='photos/default/default_user.png')
    city = models.CharField(blank=True, max_length=20)
    state = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=30)

    def __str__(self):
        return self.user.first_name

accounts/forms.py
from django import forms
from .models import Account, UserProfile
from django.contrib import messages


class RegistrationForm(forms.ModelForm):

	password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Enter Password'}))
	confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Confirm Password'}))


	class Meta:
		
		model = Account
		fields = ['first_name','last_name','email', 'phone_number', 'password']



	def clean(self):
		
		cleaned_data = super(RegistrationForm, self).clean()
		password = cleaned_data.get('password')
		confirm_password = cleaned_data.get('confirm_password')

		if password != confirm_password:
			raise forms.ValidationError('Password does not match!')

			

	def __init__(self, *args, **kwargs):

		super(RegistrationForm, self).__init__(*args, **kwargs)

		self.fields['first_name'].widget.attrs['placeholder']='First Name'
		self.fields['email'].widget.attrs['placeholder']='Your Email'
		self.fields['phone_number'].widget.attrs['placeholder']='Phone Number'
		self.fields['last_name'].widget.attrs['placeholder']='Last Name'

		for field in self.fields:
			self.fields[field].widget.attrs['class'] = 'form-control'


class UserForm(forms.ModelForm):

	class Meta:

		model = Account
		fields = ['first_name', 'last_name', 'phone_number']

	def __init__(self, *args, **kwargs):
		super(UserForm, self).__init__(*args, **kwargs)
		for field in self.fields:
			self.fields[field].widget.attrs['class']= 'form-control'


class UserProfileForm(forms.ModelForm):
	
	profile_image = forms.ImageField(required=False, error_messages={'Invalid':('Image Files Only.')}, widget=forms.FileInput)
	class Meta:
		
		model = UserProfile
		fields = ['address_line_1', 'address_line_2', 'profile_image', 'city', 'state', 'country']

	def __init__(self, *args, **kwargs):
		super(UserProfileForm, self).__init__(*args, **kwargs)
		for field in self.fields:
			self.fields[field].widget.attrs['class']= 'form-control'

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import RegistrationForm, UserForm, UserProfileForm
from .models import Account, UserProfile
from django.conf import settings
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
#Django Verification module 
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
from orders.models import Order
from cart.views import _cart_id
from cart.models import Cart, CartItem
import requests
# Create your views here.


def register(request):

	if request.user.is_authenticated == False:
		if request.method == 'POST':
			form = RegistrationForm(request.POST)
			if form.is_valid():

				email = form.cleaned_data['email']
				password = form.cleaned_data['password']
				first_name = form.cleaned_data['first_name']
				last_name = form.cleaned_data['last_name']
				phone_number = form.cleaned_data['phone_number']
				username = email.split('@')[0]
				user = Account.objects.create_user(email=email, password=password, first_name=first_name, last_name=last_name, phone_number=phone_number, username=username)
				user.phone_number = phone_number # For update phone number
				user.save()

				#Accounts Email verification_Function

				current_site = get_current_site(request)
				to_mail = email
				mail_subject = 'Please active your account'
				mail_messages = render_to_string('accounts/accounts_verification_email.html', {

				'user':user,
				'domain':current_site,
				'uid':urlsafe_base64_encode(force_bytes(user.pk)),
				'token':default_token_generator.make_token(user),

				})
				
				email_send = EmailMessage(mail_subject, mail_messages, settings.EMAIL_HOST_USER, to=[to_mail])
				email_send.fail_silently = False
				email_send.send()

				return redirect('/accounts/log_in/?command=verification&email='+email)
		else:
			form = RegistrationForm()
	else:
		messages.success(request, 'You are already logged in.')
		return redirect('accounts:dashboard')

		
	context = {
		'form':form
	}
	return render(request, 'accounts/register.html', context)


def log_in(request):

	if request.user.is_authenticated:

		messages.success(request, 'You are already logged in.')
		return redirect('accounts:dashboard')
	
	else:	

		if request.method == 'POST':		
			email = request.POST['email']
			password = request.POST['password']

			user = auth.authenticate(email=email, password=password)

			if user is not None:

				try:
					cart = Cart.objects.get(cart_id=_cart_id(request))
					is_cart_item_exist = CartItem.objects.filter(cart=cart).exists()

					if is_cart_item_exist:

						cart_item = CartItem.objects.filter(cart=cart)

						# Adding Product Variations by Cart Id from Guest user.
						product_variations = [] #[['blue', 'medium'],['blue', 'medium'],['blue', 'medium']] 
						product_quaintity = []
						for item in cart_item:
							variation = item.product_variation.all()
							product_variations.append(list(variation))
							quantity = item.quality
							product_quaintity.append(quantity)


						# Adding Product Variations from Authenticated user
						cart_item = CartItem.objects.filter(user=user)
						ex_variation_list = [] #[['blue', 'medium'], ['Red', 'medium']]
						cart_item_id = []
						count = 0 #for getting product quantity

						for item in cart_item:
							ex_variation = item.product_variation.all()
							ex_variation_list.append(list(ex_variation))
							cart_item_id.append(item.id)

				
						for pr in product_variations:
							count += 1
							if pr in ex_variation_list:
								index = ex_variation_list.index(pr)
								item_id = cart_item_id[index]
								item_quantity = product_quaintity[count -1]
								item = CartItem.objects.get(id=item_id)
								item.quality += item_quantity
								item.user = user
								item.save()

							else:
								cart_items = CartItem.objects.filter(cart=cart)
								for item in cart_items:
									variation = list(item.product_variation.all())
									if variation not in ex_variation_list:
										item.user = user
										item.save()

				except:
					pass

				auth.login(request, user)
				messages.success(request, 'You are now logged in.')
				url = request.META.get('HTTP_REFERER')  # http://127.0.0.1:8000/accounts/log_in/?next=/cart/checkout/
				try:
					query = requests.utils.urlparse(url).query  # next=/cart/checkout/
					params =dict(x.split('=') for x in query.split('&')) # {'next': '/cart/checkout/'}
					if 'next' in params:
						next_page = params['next']
						return redirect(next_page)
				except:
					return redirect('accounts:dashboard')
			else:
				messages.error(request, 'Invalid Email or Password.')
				return redirect('accounts:log_in')
		
			

	return render(request, 'accounts/login.html')

@login_required(login_url='accounts:log_in')
def log_out(request):
	if request.user.is_authenticated:
		auth.logout(request)
		messages.success(request, 'You are now logged out.')
	else:
		messages.success(request, 'You are already logged out.')
		return redirect('accounts:log_in')
	return redirect('accounts:log_in')




def activate(request, uidb64, token):
	
	try:
		uid = urlsafe_base64_decode(uidb64).decode()
		user = Account._default_manager.get(pk=uid)
	except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
		user = None

	if user is not None and default_token_generator.check_token(user, token):
		user.is_active = True
		user.save()
		messages.success(request, 'Congratulations! Your account is activated.')
		return redirect('accounts:log_in')

	else:
		messages.error(request, 'Invalid activation link.')
		return redirect('accounts:register')


@login_required(login_url='accounts:log_in')
def dashboard(request):
	current_user = request.user
	if request.user.is_authenticated:
		order = Order.objects.order_by('-created_at').filter(user=request.user, is_ordered=True)
		order_count = order.count()
		
		#After login it will create userprofile
		try:
			userprofile = UserProfile.objects.get(user=request.user)
		except:
			userprofile = UserProfile.objects.create(user=request.user)
	
		context = {
			'order_count':order_count,
			'current_user':current_user,
			'userprofile': userprofile,
		}	
	return render(request, 'accounts/dashboard.html', context)

@login_required(login_url='accounts:log_in')
def my_orders(request):
	order = Order.objects.filter(user=request.user, is_ordered=True).order_by('-created_at')
	context = {'order':order}
	return render(request, 'accounts/my_orders.html', context)


@login_required(login_url='accounts:log_in')
def edit_profile(request):

	userprofile = UserProfile.objects.get(user=request.user)
	try:

		if request.method == 'POST':
			userform = UserForm(request.POST, instance=request.user)
			userprofileform = UserProfileForm(request.POST, request.FILES, instance=userprofile)
			if userform.is_valid() and userprofileform.is_valid():
				userform.save()
				userprofileform.save()
				messages.success(request, 'Profile information has been updated.')
				return redirect('accounts:edit_profile') 

		else:
			userform = UserForm(instance=request.user)
			userprofileform = UserProfileForm(instance=userprofile)
	except:
		pass

	context = {'userform':userform, 'userprofileform':userprofileform, 'userprofile':userprofile}

	return render(request, 'accounts/edit_profile.html', context)

	
@login_required(login_url='accounts:log_in')
def change_password(request):
	
	if request.method == 'POST':
		print('POST method True')
		current_password = request.POST['current_password']
		new_password = request.POST['new_password']
		confirm_password = request.POST['confirm_password']

		user = Account.objects.get(email__exact=request.user.email)

		if new_password == confirm_password:
			success = user.check_password(current_password)
			if success:
				user.set_password(new_password)
				user.save()
				auth.logout(request)
				messages.success(request, 'Your password has been updated, login to continue!')
				return redirect('accounts:log_in')
			else:
				messages.error(request, 'Your current password does not match.')
				return redirect('accounts:change_password')
		else:
			messages.error(request, 'Password does not match.')
			return redirect('accounts:change_password')


	return render(request, 'accounts/change_password.html')

def reset_password(request):

	if request.method == 'POST':
		email = request.POST['email']

		if Account.objects.filter(email__exact=email).exists():
			user = Account.objects.get(email__exact=email)
			current_site = get_current_site(request)
			to_mail = email
			mail_subject = 'Reset your password.'
			mail_messages = render_to_string('accounts/reset_password_email.html', {

			'user':user,
			'domain':current_site,
			'uid':urlsafe_base64_encode(force_bytes(user.pk)),
			'token':default_token_generator.make_token(user),

			})	

			send_mail = EmailMessage(mail_subject, mail_messages, to=[to_mail])
			send_mail.fail_silently = False
			send_mail.send()
			messages.success(request, 'Password reset email has been send to your email address.')
			return redirect('accounts:log_in')
		else:
			messages.error(request, 'Account does not exist!')
			return redirect('accounts:reset_password')

	return render(request, 'accounts/password_reset.html')



def reset_password_validate(request, uidb64, token):

	try:
		uid = urlsafe_base64_decode(uidb64).decode()
		user = Account._default_manager.get(pk=uid)

	except(ValueError, TypeError, OverflowError, Account.DoesNotExist):
		user = None


	if user is not None and default_token_generator.check_token(user, token):
			
		request.session['uid'] = uid
		messages.success(request, 'Please reset your password.')

templates/accounts/accounts_verification_email.html
{% autoescape off %}

Hi {{user.first_name}},

Please click on below link to active your account.
http://{{domain}}{% url 'accounts:activate' uidb64=uid token=token %}

If you think it's not you, please ingore this email.

{% endautoescape %}

templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="section-conten padding-y bg">
{% include 'includes/alerts.html' %}

<div class="container">
  <div class="row">
  {% include 'includes/dashboard_sidebar.html' %}
  <main class="col-md-9">
    <article class="card">

    <header class="card-header">
      <strong class="d-inline-block mr-3">Change Your Password:</strong>
    </header>

    <div class="card-body">
      <div class="row"> 
        <div class="col-md-12"> 
          <div class="mx-auto" style="max-width: 400px; ">
        <form action="{% url 'accounts:change_password' %}" method="POST"> 
          {% csrf_token %}

           <div class="form-group">
              <input type="password" class="form-control" placeholder="Current Password" name="current_password" required>
           </div> <!-- form-group// -->
    
          <div class="form-group">
              <input type="password" class="form-control" placeholder="Create New Password" name="new_password" required>
           </div> <!-- form-group// -->

           <div class="form-group">
              <input type="password" class="form-control" placeholder="Confirm New Password" name="confirm_password" required>
           </div> <!-- form-group// -->


        
          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block"> Change Password  </button>
          </div> <!-- form-group// -->  

        </form>
      </div>

       </div>
      </div> <!-- row.// -->
    </div> <!-- card-body .// -->
    </article> <!-- order-group.// --> 
  </main>
</div> <!-- row.// -->
</div>
</section>
{% endblock %}

templates/accounts/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="section-conten padding-y bg">
{% include 'includes/alerts.html' %}

<div class="container">
	<div class="row">
	{% include 'includes/dashboard_sidebar.html' %}
	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Logged in as:</strong>
			<span>{{user.full_name}}</span>
		</header>
		<div class="card-body">
			<div class="row"> 
				<div class="col-md-6">
					<div class="card" style="text-align: center;">
						<div class="card-body">
							<h5 class="card-title">Total Orders</h5>
							<h4>{{order_count}}</h4>
							<a href="{% url 'accounts:my_orders' %}">View Orders</a>
						</div>
					</div>
				</div>

				<div class="col-md-6">
					<div class="card" style="text-align: center;">
						<div class="card-body">
							<img src="{% get_media_prefix %}{{userprofile.profile_image}}" width="50px" height="50px" style="border-radius:50%;">
							<p class="mb-0">{{user.full_name}}</p>
							<p class="mb-0">{{user.email}} | {{user.phone_number}}</p>
						</div>
					</div>
				</div>
			</div> <!-- row.// -->
		</div> <!-- card-body .// -->
		<div class="table-responsive">
		
		</div> <!-- table-responsive .end// -->
		</article> <!-- order-group.// --> 
	</main>
</div> <!-- row.// -->
</div>


</section>

{% endblock %}

templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="section-conten padding-y bg">
{% include 'includes/alerts.html' %}

<div class="container">
	<div class="row">
	{% include 'includes/dashboard_sidebar.html' %}
	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Edit User Info:</strong>
		</header>
		<div class="card-body">
			<div class="text-center">
				{% if userprofile.profile_image %}
				<img src="{{userprofile.profile_image.url}}" alt="Profile Image" width="100" style="border-radius: 50%; margin: 30px;">
				
				{% endif %}
			</div>
			<div class="row"> 
				<div class="col-md-12">
					<form action="{% url 'accounts:edit_profile' %}" method="POST" enctype="multipart/form-data"> 
						{% csrf_token %}
						<div class="form-row">
							<div class="form-group col-md-6">
								<label>First Name</label>
								{{userform.first_name}}
							</div>
							<div class="form-group col-md-6">
								<label>Last Name</label>
								{{userform.last_name}}
							</div>
						</div>

						<div class="form-row">
							<div class="form-group col-md-6">
								<label> Phone Number</label>
								{{userform.phone_number}}
							</div>
							<div class="form-group col-md-6">
								<label>Profile Image</label>
								{{userprofileform.profile_image}}
							</div>
						</div>

						<div class="form-row">
							<div class="form-group col-md-6">
								<label>Address Line 1</label>
								{{userprofileform.address_line_1}}
							</div>
							<div class="form-group col-md-6">
								<label>Address Line 2</label>
								{{userprofileform.address_line_2}}
							</div>
						</div>

						<div class="form-row">
							<div class="form-group col-md-4">
								<label>City</label>
								{{userprofileform.city}}
							</div>
							<div class="form-group col-md-4">
								<label>State</label>
								{{userprofileform.state}}
							</div>
							<div class="form-group col-md-4">
								<label>Country</label>
								{{userprofileform.country}}
							</div>
						</div>
						<input type="submit" value="Save" class="btn btn-primary" style="width: 150px;">
					</form>
				</div>
			</div> <!-- row.// -->
		</div> <!-- card-body .// -->
		<div class="table-responsive">
		
		</div> <!-- table-responsive .end// -->
		</article> <!-- order-group.// --> 
	</main>
</div> <!-- row.// -->
</div>


</section>

{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

{% if request.GET.command == 'verification' %}

  <div class="container mx-auto alert alert-info text-center" role="alert" style="max-width: 1024px; margin-top:100px;">
  Thank you for registering with us. we have send you a verification email to your email address {{request.GET.email}}. please activate your account by clicking the link.
  <br><br>
  Already verified? <a href="{% url 'accounts:log_in' %}">Login</a>
  </div>

{% else %}

<!-- ============================ COMPONENT LOGIN   ================================= -->


  {% include 'includes/alerts.html' %}
	<div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
    <form method="POST" action="{% url 'accounts:log_in' %}">
      {% csrf_token %}
      <div class="card-body">
      <h4 class="card-title mb-4">Sign in</h4>
      <form>
          <div class="form-group">
			 <input type="email" class="form-control" placeholder="Email Address" name="email">
          </div> <!-- form-group// -->
          <div class="form-group">
			<input type="password" class="form-control" placeholder="Password" name="password">
          </div> <!-- form-group// -->
          
          <div class="form-group">
          	<a href="{% url 'accounts:reset_password' %}" class="float-right">Forgot password?</a> 
           
          </div> <!-- form-group form-check .// -->
          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block"> Login  </button>
          </div> <!-- form-group// -->    
      </form>
      </div> <!-- card-body.// -->
    </div> <!-- card .// -->
    </form>

     <p class="text-center mt-4"> Don't have account? <a href="{% url 'accounts:register' %}"> Sign up </a></p>
     <br><br>

<!-- ============================ COMPONENT LOGIN  END.// ================================= -->

{% endif %}

</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/logout.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% endblock %}

templates/accounts/my_orders.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="section-conten padding-y bg">
{% include 'includes/alerts.html' %}

<div class="container">
	<div class="row">
	{% include 'includes/dashboard_sidebar.html' %}
	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Orders History:</strong>
		</header>
		<div class="card-body">
			<div class="row"> 
				<div class="col-md-12">
					<table class="table table-hover">
					  <thead>
					    <tr>
					      <th scope="col">Order #</th>
					      <th scope="col">Billing Name</th>
					      <th scope="col">Phone</th>
					      <th scope="col">Order Total</th>
					      <th scope="col">Order Date</th>
					    </tr>
					  </thead>
					  <tbody>
					  	{% for order in order %}
					    <tr>
					      <th scope="row"><a href="{% url 'orders:order_details' order.order_number %}">{{order.order_number}}</a></th>
					      <td>{{order.full_name}}</td>
					      <td>{{order.phone}}</td>
					      <td>{{order.order_total}}</td>
					      <td>{{order.created_at}}</td>
					    </tr>
					    {% endfor %}
					  </tbody>
					</table>
				</div>
			</div> <!-- row.// -->
		</div> <!-- card-body .// -->
		<div class="table-responsive">
		
		</div> <!-- table-responsive .end// -->
		</article> <!-- order-group.// --> 
	</main>
</div> <!-- row.// -->
</div>


</section>

{% endblock %}

templates/accounts/password_reset.html
{% extends 'base.html' %}

{% block content %}

<section class="section-conten padding-y" style="min-height:84vh">

<!-- ============================ COMPONENT LOGIN   ================================= -->

  {% include 'includes/alerts.html' %}
	<div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
    <form method="POST" action="{% url 'accounts:reset_password' %}">
      {% csrf_token %}
      <div class="card-body">
      <h4 class="card-title mb-4">Forgot Password</h4>
      <form>
          <div class="form-group">
			 <input type="email" class="form-control" placeholder="Email Address" name="email">
          </div> <!-- form-group// -->
          
          <div class="form-group">
          	<a href="{% url 'accounts:log_in' %}" class="float-right">Got password! Login.</a> 
           
          </div> <!-- form-group form-check .// -->
          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block"> Reset Password  </button>
          </div> <!-- form-group// -->    
      </form>
      </div> <!-- card-body.// -->
    </div> <!-- card .// -->
    </form>

     <p class="text-center mt-4"> Don't have account? <a href="{% url 'accounts:register' %}"> Sign up </a></p>
     <br><br>

<!-- ============================ COMPONENT LOGIN  END.// ================================= -->



</section>
{% endblock %}

templates/accounts/reset_password_email.html
{% autoescape off %}

Hi {{user.first_name}},

As requested, please click below link ti reset your password.
http://{{domain}}{% url 'accounts:reset_password_validate' uidb64=uid token=token %}

If you think it's not you. please ignore this mail.

{% endautoescape %}

templates/accounts/reset_password_process.html
{% extends 'base.html' %}

{% block content %}

<section class="section-conten padding-y" style="min-height:84vh">

<!-- ============================ COMPONENT LOGIN   ================================= -->

  {% include 'includes/alerts.html' %}
	<div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
    <form method="POST" action="{% url 'accounts:reset_password_process' %}">
      {% csrf_token %}
      <div class="card-body">
      <h4 class="card-title mb-4">Reset Password</h4>
      <form>
          <div class="form-group">
			 <input type="password" class="form-control" placeholder="Password" name="password">
          </div> <!-- form-group// -->
          <div class="form-group">
       <input type="password" class="form-control" placeholder="Confirm Password" name="confirm_password">
          </div> <!-- form-group// -->
          
          <div class="form-group">
          	<a href="{% url 'accounts:log_in' %}" class="float-right">Got password! Login.</a> 
           
          </div> <!-- form-group form-check .// -->
          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block"> Submit  </button>
          </div> <!-- form-group// -->    
      </form>
      </div> <!-- card-body.// -->
    </div> <!-- card .// -->
    </form>

     <p class="text-center mt-4"> Don't have account? <a href="{% url 'accounts:register' %}"> Sign up </a></p>
     <br><br>

<!-- ============================ COMPONENT LOGIN  END.// ================================= -->



</section>
{% endblock %}