accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [

	path('register/', views.register, name='register'),
	path('log_in/', views.log_in, name='log_in'),
	path('log_out/', views.log_out, name='log_out'),
	path('reset_password/', views.reset_password, name='reset_password'),
	
	path('activate/<uidb64>/<token>/', views.activate, name='activate'),
	path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),
	path('reset_password_process/', views.reset_password_process, name='reset_password_process'),
	path('', views.dashboard, name='dashboard'),
	path('my_orders/', views.my_orders, name='my_orders'),
	path('edit_profile/', views.edit_profile, name='edit_profile'),
	path('change_password/', views.change_password, name='change_password'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:product_id>/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('delete_cart_item/<int:product_id>/<int:cart_item_id>/', views.delete_cart_item, name='delete_cart_item'),

    path('checkout/', views.checkout, name='checkout'),
    
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [

    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='product_by_categroy'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_details, name='product_details'),
    path('search/', views.search, name='search'),
   path('submitreview/<int:product_id>/', views.submit_review, name='submit_review'),

]

templates/includes/alerts.html
{% if form.email.errors %}

	{% for message in form.email.errors %}
	<div id="message" class="container">
		<div class="alert alert-danger" role="alert">
		<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
		{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
		{{ message }}

		</div>
	</div>
	{% endfor %}

{% endif %}




{% if form.non_field_errors %}

	{% for message in form.non_field_errors %}
	<div id="message" class="container">
		<div class="alert alert-danger text-center" role="alert">
		<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
		{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
		{{ message }}

		</div>
	</div>
	{% endfor %}

{% endif %}


{% if messages %}

	{% for message in messages %}

	<div id="message" class="container" style="padding-top: 10px;">
		<div class="alert alert-success" role="alert">
		<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
		{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
		{{ message }}

		</div>
	</div>
	{% endfor %}

{% endif %}

templates/includes/dashboard_sidebar.html
<aside class="col-md-3">
		<!--   SIDEBAR   -->
		<ul class="list-group">
			<a class="list-group-item {% if '/accounts/' == request.path %} active {% endif %}" href="{% url 'accounts:dashboard' %}"> Dashboard </a>
			<a class="list-group-item {% if '/accounts/my_orders/' == request.path %} active {% endif %}" href="{% url 'accounts:my_orders' %}"> Orders </a>
			<a class="list-group-item {% if '/accounts/edit_profile/' == request.path %} active {% endif %}" a href="{% url 'accounts:edit_profile' %}"> Edit Profile </a>
			<a class="list-group-item {% if '/accounts/change_password' == request.path %} active {% endif %}" href="{% url 'accounts:change_password' %}">Change Password <a>
			
		</ul>
		<br>
		<a class="btn btn-light btn-block" href="{% url 'accounts:log_out' %}"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a> 
		<!--   SIDEBAR .//END   -->
	</aside>

templates/includes/footer.html
<!-- ========================= FOOTER ========================= -->
<footer class="section-footer border-top">
	<div class="container">
		<section class="footer-bottom border-top row">
			<div class="col-md-2">
				<p class="text-muted"> &copy 2019 Company name </p>
			</div>
			<div class="col-md-8 text-md-center">
				<span  class="px-2">info@pixsellz.io</span>
				<span  class="px-2">+879-332-9375</span>
				<span  class="px-2">Street name 123, Avanue abc</span>
			</div>
			<div class="col-md-2 text-md-right text-muted">
				<i class="fab fa-lg fa-cc-visa"></i>
				<i class="fab fa-lg fa-cc-paypal"></i>
				<i class="fab fa-lg fa-cc-mastercard"></i>
			</div>
		</section>
	</div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
	$(document).ready(function(){
		$('.thumb a').click(function(e){
			e.preventDefault();
			$('.mainimage img').attr('src', $(this).attr("href"));

		})
		})
	
</script>

templates/includes/navbar.html
{% load static %}

<header class="section-header">
<nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
<div class="container">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTop4">
    <ul class="navbar-nav mr-auto">
    	<li class="nav-item dropdown">
		 	<a href="#" class="nav-link">   English </a>
		    
		</li>
		<li class="nav-item dropdown">
			<a href="#" class="nav-link"> USD </a>
		</li>
    </ul>
    <ul class="navbar-nav">
		<li><a href="#" class="nav-link"> <i class="fa fa-envelope"></i> Email </a></li>
		<li><a href="#" class="nav-link"> <i class="fa fa-phone"></i> Call us </a></li>
	</ul> <!-- list-inline //  -->
  </div> <!-- navbar-collapse .// -->
</div> <!-- container //  -->
</nav>

<section class="header-main border-bottom">
	<div class="container">
<div class="row align-items-center">
	<div class="col-lg-2 col-md-3 col-6">
		<a href="{% url 'home' %}" class="brand-wrap">
			<img class="logo" src="{% static './images/logo.png' %}">
		</a> <!-- brand-wrap.// -->
	</div>
	<div class="col-lg col-sm col-md col-6 flex-grow-0">
		<div class="category-wrap dropdown d-inline-block float-right">
			<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> 
				<i class="fa fa-bars"></i> All category 
			</button>
			<div class="dropdown-menu">
				<a class="dropdown-item" href="{% url 'store:store' %}">All Categories</a>
				{% for category_link in links %}
				<a class="dropdown-item" href="{{ category_link.get_url }}">{{category_link}}</a>
				{% endfor %}
				
				
			</div>
		</div>  <!-- category-wrap.// -->
	</div> <!-- col.// -->
	<a href="{% url 'store:store' %}" class="btn btn-outline-primary">Store</a>
	<div class="col-lg  col-md-6 col-sm-12 col">
		<form action="{% url 'store:search' %}" class="search" method="GET">
			<div class="input-group w-100">
			    <input type="text" class="form-control" style="width:60%;" placeholder="Search" name="keyword">
			    
			    <div class="input-group-append">
			      <button class="btn btn-primary" type="submit">
			        <i class="fa fa-search"></i>
			      </button>
			    </div>
		    </div>
		</form> <!-- search-wrap .end// -->
	</div> <!-- col.// -->
	<div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">

				{% if user.is_authenticated %}
				<div class="d-flex justify-content-end mb-3 mb-lg-0">
					<div class="widget-header">
						<small class="title text-muted">Welcome {{user.first_name}} !</small>
						<div> 
							<a href="{% url 'accounts:dashboard' %}">Dashboard</a> <span class="dark-transp"> | </span>
							<a href="{% url 'accounts:log_out' %}"> Logout</a>
						</div>
					</div>
					{% else %}
							<div class="widget-header">
							<small class="title text-muted">Welcome Guest!</small>
							<div> 
								<a href="{% url 'accounts:log_in' %}">Sign in</a> <span class="dark-transp"> | </span>
								<a href="{% url 'accounts:register' %}"> Register</a>
							</div>
						</div>
					{% endif %}
					<a href="{% url 'cart:cart' %}" class="widget-header pl-3 ml-3">
						<div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
						<span class="badge badge-pill badge-danger notify">{{cart_count}}</span>
					</a>
				</div> <!-- widgets-wrap.// -->
			</div> <!-- col.// -->
</div> <!-- row.// -->
	</div> <!-- container.// -->
</section> <!-- header-main .// -->




</header> <!-- section-header.// -->