accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [

	path('register/', views.register, name='register'),
	path('log_in/', views.log_in, name='log_in'),
	path('log_out/', views.log_out, name='log_out'),
	path('reset_password/', views.reset_password, name='reset_password'),
	
	path('activate/<uidb64>/<token>/', views.activate, name='activate'),
	path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),
	path('reset_password_process/', views.reset_password_process, name='reset_password_process'),
	path('', views.dashboard, name='dashboard'),
	path('my_orders/', views.my_orders, name='my_orders'),
	path('edit_profile/', views.edit_profile, name='edit_profile'),
	path('change_password/', views.change_password, name='change_password'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:product_id>/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('delete_cart_item/<int:product_id>/<int:cart_item_id>/', views.delete_cart_item, name='delete_cart_item'),

    path('checkout/', views.checkout, name='checkout'),
    
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [

    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='product_by_categroy'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_details, name='product_details'),
    path('search/', views.search, name='search'),
   path('submitreview/<int:product_id>/', views.submit_review, name='submit_review'),

]

store/models.py
from django.db import models
from core.models import Category
from django.urls import reverse
from accounts.models import Account
from django.db.models import Avg,Count
# Create your models here.


class Product(models.Model):

    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.PositiveIntegerField()
    images = models.ImageField(upload_to='photos/product')
    stock = models.PositiveIntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product_name

    def get_url(self):
        return reverse('store:product_details', args=[self.category.slug, self.slug])

    def avarage(self):
        rating = ReviewRating.objects.filter(product=self, status=True).aggregate(avarage=Avg('rating'))
        avg = 0
        if rating['avarage'] is not None:
            avg = float(rating['avarage'])
        return avg

    def rating_count(self):
        rating = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count = 0
        if rating['count'] is not None:
            count = int(rating['count'])
        return count

class VariationsManager(models.Manager):

    def colors(self):
        return super(VariationsManager, self).filter(variation_category='color', is_available=True)

    def sizes(self):
        return super(VariationsManager, self).filter(variation_category='size', is_available=True)



variation_category_choices = (
            ('color','color'),
            ('size','size'),
    ) 


class Variation(models.Model):

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=200, choices=variation_category_choices)
    variation_value = models.CharField(max_length=200, default='Single')
    is_available = models.BooleanField(default=True)

    objects = VariationsManager()

    def __str__(self):
        return f'{self.variation_category} {self.variation_value}'


class ReviewRating(models.Model):

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    review = models.CharField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=100, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.review


class ProductImage(models.Model):

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    images = models.ImageField(upload_to='photos/product', null=True)


    def __str__(self):
        return self.product.product_name


    class Meta:

        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'

store/forms.py
from django import forms
from .models import ReviewRating

class ReviewRatingForm(forms.ModelForm):

	class Meta:
		
		model = ReviewRating
		fields = ['rating', 'review']

store/views.py
from multiprocessing import context
from django.shortcuts import render, get_object_or_404, HttpResponse, redirect
from .models import Product, ReviewRating, ProductImage
from core.models import Category
from django.core.paginator import Paginator
from django.db.models import Q
from .forms import ReviewRatingForm
from django.contrib import messages
from orders.models import OrderProduct
from accounts.models import UserProfile
# Create your views here!.


def store(request, category_slug=None):
    categories = None
    product = None

    if category_slug != None:
        categories = get_object_or_404(Category, slug=category_slug)
        product = Product.objects.filter(category=categories, is_available=True)
        product_count = product.count()
        paginator = Paginator(product, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)

    else:
        product = Product.objects.filter(is_available=True)
        product_count = product.count()
        paginator = Paginator(product, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)

    context = {'products': paged_products, 'product_count': product_count, }
    return render(request, 'store/store.html', context)


def product_details(request, category_slug, product_slug):

    orderproduct = None
    try:
        product_details = Product.objects.get(category__slug=category_slug, slug=product_slug)
    except Exception as e:
        return e

    try:
        if request.user.is_authenticated:
            orderproduct = OrderProduct.objects.filter(user=request.user, product_id=product_details.id).exists()
    except OrderProduct.DoesNotExist:
        orderproduct = None

    review = ReviewRating.objects.filter(product_id=product_details.id, status=True)
    product_gallery = ProductImage.objects.filter(product__id=product_details.id)
    context = {'product_details': product_details, 'orderproduct':orderproduct, 'review':review, 'product_gallery':product_gallery}
    return render(request, 'store/product_details.html', context)


def search(request, product=None, product_count=0):
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            product = Product.objects.order_by('-created_date').filter(Q(description__icontains=keyword) | Q(product_name__icontains=keyword))
            product_count = product.count()   
          
    context = {'products': product, 'product_count': product_count}
    return render(request, 'store/store.html', context)


def submit_review(request, product_id):
    
    url = request.META.get('HTTP_REFERER')
    if request.method == "POST":

        try:
            ratings = ReviewRating.objects.get(user__id=request.user.id, product__id=product_id)
            form = ReviewRatingForm(request.POST, instance=ratings)
            form.save()
            messages.success(request, 'Thank you! Your review has been updated.')
            return redirect(url)
        
        except:
            form = ReviewRatingForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.user_id = request.user.id
                data.save()
                messages.success(request, 'Thank you! Your review has been submitted.')
                return redirect(url)

templates/store/product_details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
<div class="card">
	<div class="row no-gutters">
		<aside class="col-md-6">
<article class="gallery-wrap"> 
	<div class="img-big-wrap mainimage">
	  <center> <a href="#"><img src="{{ product_details.images.url }}"></a> </center>
	</div> <!-- img-big-wrap.// -->
	
</article> <!-- gallery-wrap .end// -->
		<ul class="thumb">
		<li>
			<a href="{{product_details.images.url}}" target="mainimage"><img src="{{product_details.images.url}}" alt="Product Image"></a>
			{% for i in product_gallery %}
			<a href="{{i.images.url}}" target="mainimage"><img src="{{i.images.url}}" alt="Product Image"></a>
			{% endfor %}
		</li> 
		</ul>
		</aside>
		<main class="col-md-6 border-left">
<form action="{% url 'cart:add_to_cart' product_details.id %}" method="POST">
	{% csrf_token %}
<article class="content-body">

<h2 class="title">{{product_details.product_name}}</h2>
	<div class="rating-star" style="margin-top: -5px; margin-bottom: 10px;">
		<span>
			<i class="fa fa-star{% if product_details.avarage < 0.5 %}-o{% elif product_details.avarage >= 0.5 and product_details.avarage < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
			<i class="fa fa-star{% if product_details.avarage < 1.5 %}-o{% elif product_details.avarage >= 1.5 and product_details.avarage < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
			<i class="fa fa-star{% if product_details.avarage < 2.5 %}-o{% elif product_details.avarage >= 2.5 and product_details.avarage < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
			<i class="fa fa-star{% if product_details.avarage < 3.5 %}-o{% elif product_details.avarage >= 3.5 and product_details.avarage < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
			<i class="fa fa-star{% if product_details.avarage < 4.5 %}-o{% elif product_details.avarage >= 4.5 and product_details.avarage < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
		</span> 
		<span> {{product_details.rating_count}} reviews</span>
	</div>

<div class="mb-3"> 
	<var class="price h4">${{product_details.price}}</var> 
</div> 

<p>{{product_details.description}}</p>


<hr>
	<div class="row">
		<div class="item-option-select">
			<h6>Choose Color</h6>
			<select class="form-control" name="color" required>
				{% for variation in product_details.variation_set.colors %}
					<option value="{{variation.variation_value | lower }}">{{variation.variation_value | capfirst }}</option>
				{% endfor %}
			</select>
		</div>
	</div> <!-- row.// -->
	<div class="row">
		<div class="item-option-select">
			<h6>Select Size</h6>
			<select class="form-control" name="size">
				{% for variation in product_details.variation_set.sizes %}
					<option value="{{variation.variation_value | lower }}">{{variation.variation_value | capfirst }}</option>
				{% endfor %}
			</select>
		</div>
	</div> <!-- row.// -->
	<hr>
	{% if product_details.stock <= 0 %}
		<h5 style="color: blue"> Out of stock </h5>
	{% else %}
	<button type="submit" href="{% url 'cart:add_to_cart' product_details.id %}" class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </button>
	{% endif %}
</article> <!-- product-info-aside .// -->
</form>
		</main> <!-- col.// -->
	</div> <!-- row.// -->
</div> <!-- card.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

<br>

<div class="row">
			<div class="col-md-9">

	<header class="section-heading">
		<h3>Customer Reviews </h3> 
		<span> 
			<div class="rating-star">
					<span>
						<i class="fa fa-star{% if product_details.avarage < 0.5 %}-o{% elif product_details.avarage >= 0.5 and product_details.avarage < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
						<i class="fa fa-star{% if product_details.avarage < 1.5 %}-o{% elif product_details.avarage >= 1.5 and product_details.avarage < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
						<i class="fa fa-star{% if product_details.avarage < 2.5 %}-o{% elif product_details.avarage >= 2.5 and product_details.avarage < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
						<i class="fa fa-star{% if product_details.avarage < 3.5 %}-o{% elif product_details.avarage >= 3.5 and product_details.avarage < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
						<i class="fa fa-star{% if product_details.avarage < 4.5 %}-o{% elif product_details.avarage >= 4.5 and product_details.avarage < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
					</span> 
					<span> {{product_details.rating_count}} reviews</span>
				</div>
		</span>
	</header>

	<form action="{% url 'store:submit_review' product_details.id %}" method="POST" style="padding: 10px;"> 
		{% csrf_token %}
		<h5>Write Your Review </h5>
		<div style="margin: 10px"> 
			<!-- Rating Stars-->
			<label>How do you rate this product? </label>
			<br>
			<div class="rate"> 
				<input type="radio" name="rating" id="rate10" value="5" required> <label for="rate10" title="5"> </label>
				<input type="radio" name="rating" id="rate9" value="4.5" required><label for="rate9" title="4.5" class="half"> </label>
				<input type="radio" name="rating" id="rate8" value="4" required><label for="rate8" title="4"> </label>
				<input type="radio" name="rating" id="rate7" value="3.5" required><label for="rate7" title="3.5" class="half"> </label>
				<input type="radio" name="rating" id="rate6" value="3" required><label for="rate6" title="3"> </label>
				<input type="radio" name="rating" id="rate5" value="2.5" required><label for="rate5" title="2.5" class="half"> </label>
				<input type="radio" name="rating" id="rate4" value="2" required><label for="rate4" title="2"> </label>
				<input type="radio" name="rating" id="rate3" value="1.5" required><label for="rate3" title="1.5" class="half"> </label>
				<input type="radio" name="rating" id="rate2" value="1" required><label for="rate2" title="1"> </label>
				<input type="radio" name="rating" id="rate1" value="0.5" required><label for="rate1" title="0.5" class="half"> </label>
			</div>
			<br>
			Review:
			<textarea name="review" class="form-control" rows="4"> </textarea>
			{% include 'includes/alerts.html' %}
			{% if user.is_authenticated %}
			{% if orderproduct %}
			<input type="submit" value="Submit Review" class="btn btn-primary" style="margin-top: 10px;">
			{% else %}
			<p>You must purchase this product to make review.</p>
			{% endif %}
			{% else %}
			<p>You must be login in to post a review. <span> <a href="{% url 'accounts:log_in' %}">Login now </a> </span> </p>
			{% endif %}
		</div>

	</form>

	{% for review in review %}
	<article class="box mb-3" style="padding: 5px;">
		<div class="icontext w-100">
			<img src="{% get_media_prefix %}{{review.user.profile_image}}" class="img-xs icon rounded-circle">
			<div class="text">
				<span class="date text-muted float-md-right">{{review.updated_at}} </span>  
				<h6 class="mb-1">{{review.user.full_name}}</h6>
				<div class="rating-star">
					<span>

						<i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
						<i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
						<i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
						<i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
						<i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>

					</span> 
				</div>
				
			</div>
		</div> <!-- icontext.// -->
		<div class="mt-3" style="padding-left: 3rem;">
			<p>
				{{review.review}}
			</p>	
		</div>
	</article>
	{% endfor %}
	

	</div> <!-- col.// -->
</div> <!-- row.// -->


</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// Git Test ========================= -->


{% endblock %}

templates/store/store.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
<div class="container">

	{% if 'search' in request.path %}
	<h2 class="title-page">Search result</h2>
	{% else %}
	<h2 class="title-page">Our Store</h2>
	{% endif %}
</div> <!-- container //  -->
</section>
<!-- ========================= SECTION INTRO END// ========================= -->

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
<div class="container">

<div class="row">
	<aside class="col-md-3">
		
<div class="card">
	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Categories</h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_1">
			<div class="card-body">
				
				<ul class="list-menu">
				<li><a href="{% url 'store:store' %}">All Categories</a></li>
				{% for category_link in links %}
				<li><a href="{{ category_link.get_url }}">{{ category_link }}</a></li>
				{% endfor %}
				</ul>

			</div> <!-- card-body.// -->
		</div>
	</article> <!-- filter-group  .// -->
	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_4" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Sizes </h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_4" >
			<div class="card-body">
			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> XS </span>
			  </label>

			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> SM </span>
			  </label>

			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> LG </span>
			  </label>

			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> XXL </span>
			  </label>
		</div><!-- card-body.// -->
		</div>
	</article> <!-- filter-group .// -->
	
	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Price range </h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_3">
			<div class="card-body">
				
				<div class="form-row">
				<div class="form-group col-md-6">
				  <label>Min</label>
				  <!-- <input class="form-control" placeholder="$0" type="number"> -->
				  	<select class="mr-2 form-control">
						<option value="0">$0</option>
						<option value="50">$50</option>
						<option value="100">$100</option>
						<option value="150">$150</option>
						<option value="200">$200</option>
						<option value="500">$500</option>
						<option value="1000">$1000</option>
					</select>
				</div>
				<div class="form-group text-right col-md-6">
				  <label>Max</label>
				  	<select class="mr-2 form-control">
						<option value="50">$50</option>
						<option value="100">$100</option>
						<option value="150">$150</option>
						<option value="200">$200</option>
						<option value="500">$500</option>
						<option value="1000">$1000</option>
						<option value="2000">$2000+</option>
					</select>
				</div>
				</div> <!-- form-row.// -->
				<button class="btn btn-block btn-primary">Apply</button>
			</div><!-- card-body.// -->
		</div>
	</article> <!-- filter-group .// -->
	
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<main class="col-md-9">

<header class="border-bottom mb-4 pb-3">
		<div class="form-inline">
			<span class="mr-md-auto">{{product_count}} Items found </span>
			
		</div>
</header><!-- sect-heading -->

<div class="row">
	{% if products %}
	{% for product in products %}
	<div class="col-md-4">
		<figure class="card card-product-grid">
			<div class="img-wrap"> 
				<a href="{{product.get_url}}">
				<img src="{{ product.images.url }}">
				</a>
			</div> <!-- img-wrap.// -->
			<figcaption class="info-wrap">
				<div class="fix-height">
					<a href="{{product.get_url}}" class="title">{{product.product_name}}</a>
					<div class="price-wrap mt-2">
						<span class="price">${{product.price}}</span>

						<div class="rating-star" style="margin-top: -5px; margin-bottom: 10px;">
						<span>
							<i class="fa fa-star{% if product.avarage < 0.5 %}-o{% elif product.avarage >= 0.5 and product.avarage < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
							<i class="fa fa-star{% if product.avarage < 1.5 %}-o{% elif product.avarage >= 1.5 and product.avarage < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
							<i class="fa fa-star{% if product.avarage < 2.5 %}-o{% elif product.avarage >= 2.5 and product.avarage < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
							<i class="fa fa-star{% if product.avarage < 3.5 %}-o{% elif product.avarage >= 3.5 and product.avarage < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
							<i class="fa fa-star{% if product.avarage < 4.5 %}-o{% elif product.avarage >= 4.5 and product.avarage < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
						</span> 
						</div>
						
					</div> <!-- price-wrap.// -->
				</div>
				{% if product.stock <= 0 %}
				<a href="{{ product.get_url }}" class="btn btn-block btn-primary">Out Of Stock </a>
				{% else %}
					<a href="{% url 'cart:add_to_cart' product.id %}" class="btn btn-block btn-primary">Add To Cart </a>	
				{% endif %}
			</figcaption>
		</figure>
	</div> <!-- col.// -->
	{% endfor %}
	{% else %}
		<h5>No item found. Please try again later.</h5>
	{% endif %}
</div> <!-- row end.// -->
	

<nav class="mt-4" aria-label="Page navigation sample">


	{% if products.has_other_pages %}
  <ul class="pagination">
  		{% if products.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{products.previous_page_number}}">Previous</a></li>
    	{% else %}
    	   <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
    	{% endif %}
    	{% for i in products.paginator.page_range %}
    		{% if products.number == i %}
    <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
    		{% else %}
    	   <li class="page-item "><a class="page-link" href="?page={{i}}">{{i}}</a></li>
    	 	{% endif %}
    	{% endfor %}
    {% if products.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{products.next_page_number}}">Next</a></li>
    {% else %}
    <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
  	{% endif %}
  </ul>
  {% endif %}
</nav>

	</main> <!-- col.// -->

</div>

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}